name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Python 3.13
    runs-on: ubuntu-latest
    environment: build
    env:
      RSS_ID_URL: ${{ vars.RSS_ID_URL }}
      RSS_FEED_ALTERNATE_URL: ${{ vars.RSS_FEED_ALTERNATE_URL }}
      RSS_FEED_AUTHOR_NAME: ${{ vars.RSS_FEED_AUTHOR_NAME }}
      RSS_FEED_AUTHOR_EMAIL: ${{ vars.RSS_FEED_AUTHOR_EMAIL }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          python --version; pip --version; pipenv --version
          pipenv requirements > requirements.txt
          pip install -r requirements.txt
      - name: Generate RSS
        id: build
        run: |
          python rss.py > jobs.xml
      - name: Upload generated RSS as artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: jobs.xml